config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :machines do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :machine
end

app/models/machine.rb
class Machine < ApplicationRecord
    belongs_to :user
    has_many :bookings
    has_one_attached :photo 

    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :machines
  has_one_attached :photo 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def index
		@bookings = policy_scope(Booking).order(created_at: :desc).where(user_id: current_user)
	end


	def create
		@booking = Booking.new(booking_params)
		@machine = Machine.find(params[:machine_id])
		@booking.machine = @machine
		@booking.user = current_user
		@booking.price = (@booking.end_date - @booking.start_date + 1) * @machine.price
		authorize @booking
		if @booking.save
			redirect_to bookings_path
		else
			render 'new'
		end
	end

	def show
		# raise
		@booking = Booking.find(params[:id])
		@machine = @booking.machine
		authorize @booking
	end

	private

	def booking_params
		params.require(:booking).permit(:start_date,:end_date)
	end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]
	before_action
	def index
		@machines = policy_scope(Machine).order(created_at: :desc)
		# @machines = Machine.all

		@markers = @machines.geocoded.map do |machine|
		{
		lat: machine.latitude,
		lng: machine.longitude,
		infoWindow: render_to_string(partial: "info_window", locals: { machine: machine }),
		}
		end
	end

	def show
		@machine = Machine.find(params[:id])
		authorize @machine
    @booking = Booking.new
	end

	def new
		@machine = Machine.new
		authorize @machine
	end

	def create
		@machine = Machine.new(machine_params)
		@machine.user = current_user
		authorize @machine
		if @machine.save
			redirect_to machine_path(@machine)
		else
			render :new
		end
	end

	def edit
		@machine = Machine.find(params[:id])
		authorize @machine
	end

	def update
		@machine = Machine.find(params[:id])
		@machine.update(machine_params)
		authorize @machine
		if @machine.save
		  redirect_to machine_path(@machine)
		else
		  render :edit
		end
	end

	private

	def machine_params
		params.require(:machine).permit(:name, :description, :price, :address, :condition, :photo, :capacity, :category)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <p><%#= @booking.price.to_s %></p>
  <h3 class="bookings-title font-weight-bold">Mes réservations</h3>
  <% @bookings.each do |booking| %>
    <div class="card-booking mb-4">
      <%= cl_image_tag booking.machine.photo.key %>
      <div class="card-booking-infos">
        <div>
          <div class="d-flex align-items-center product-name mr-5">
            <h1 style="font-size:30px; margin-bottom: 0px"><%= booking.machine.name %></h1>
          </div>
        </div>
      </div>
      <div class="d-flex card-booking-infos flex-grow-1 justify-content-end align-items-center" style="position: unset;margin-right: 37px;">
        <div class="range-dates mr-5 p-4">
          <div class="start-date-booking">
            Début de location: <b><%= booking.start_date %></b>
          </div>
          <div class="end-date-booking">
            Fin de location: <b><%= booking.end_date %></b>
          </div>
        </div>
        <h2 style="font-size: 20px; padding: 10px 17px; background-color: #d9d9da; border-radius: 9px;"><%= number_with_precision(booking.price, precision: 2) %> €</h2>
      </div>
    </div>
  <% end %>



 
  <%= link_to "Retour aux appareils", machines_path, class:"btn btn-discover mt-3" %>
  <br>
  <%#= cl_image_tag @machine.photo, height: 300, width: 400, crop: :fill %>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Réserver cet appareil</h1>
        <div id="booking-form" data-price="<%= @machine.price %>">

          <%= simple_form_for [@machine, @booking] do |f| %>
             <%= f.input  :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
             <%= f.input  :end_date,   as: :string, required: false, input_html: {id: "range_end"} %>
             <%= f.button :submit, class: 'btn btn-primary' %>
          <% end %>
        </div>
        <div id="total-amount">
        </div>
      </div>
    </div>
  </div>

app/views/bookings/show.html.erb
<div class="container">
  <p><%#= @booking.price.to_s %></p>
  <h3>Your booking</h3>
  <% @bookings.each do |booking| %>
    <div class="card-product">
      <%= cl_image_tag booking.machine.photo.key %>
      <div class="card-product-infos">
        <div>
          <div class="d-flex align-items-center product-name mr-5">
            <h1 style="font-size:30px; margin-bottom: 0px"><%= booking.machine.name %></h1>
          </div>
        </div>
      </div>
      <div class="d-flex card-product-infos justify-content-end align-items-center" style="position: unset;margin-right: 37px;">
        <div class="range-dates mr-5 p-4">
          <div class="start-date-booking">
            Rental starting date: <b><%= booking.start_date %></b>
          </div>
          <div class="end-date-booking">
            Rental ending date: <b><%= booking.end_date %></b>
          </div>
        </div>
        <h2 style="font-size: 20px; padding: 10px 17px; background-color: #d9d9da; border-radius: 9px;"><%= booking.price %></h2>
      </div>
    </div>
  <% end %>



  <div class="card-product">
    <%= cl_image_tag(@booking.machine.photo.key,
        width: 400, height: 300, crop: :fill) %>
      <div class="card-product-infos">  
        <div class="d-flex justify-content-between">
        <div class="machine-name">
          <p> Machine name </p>
          <h1><%= @machine.name %></h1>
        </div>
          <div>
            <p> Total amount </p>
            <h1><%= @booking.price %> </h1>
          </div>
        <div class="col align-self-center">
          <div>       
            <p> Rental starting date </p>
            <%= @booking.start_date %>
          </div>

          <div>
            <p>Rental ending date </p>
            <%= @booking.start_date %>
          </div>
         </div>
      </div>
    </div>
  </div>

 
  <%= link_to "Back to all machines", machines_path, class:"btn btn-primary" %>
  <br>
  <%#= cl_image_tag @machine.photo, height: 300, width: 400, crop: :fill %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnp551</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/machines/_info_window.html.erb
<div class="pop-up-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path machine.photo.key, crop: :fill %>')"></div>

<div>
  <h2><%= machine.name %></h2>
  <p><%= machine.address %></p>
</div>

<div class="btn-yellow" style="text-decoration: none"><%= link_to "Reserver", machine_path(machine) %></div>

app/views/machines/index.html.erb
<div class="container">
  <%= render "shared/searchbar" %>
</div>
<div class="main-container">
  <div class="index-cards">
    <% @machines.each do |machine| %>  
      <div class="card-details">
        <%= link_to machine_path(machine) do %>
          <% if machine.photo.attached? %>
            <%= cl_image_tag machine.photo.key %>
          <% end  %>
          <div class="card-text-elements">
            <div class="card-title-description">
              <h2><%= link_to machine.name, machine_path(machine) %></h2>
            </div>
            <div class="card-icons">
              <div>
                <p>💰</p>
                <h3><%= machine.price %>€/ jour</h3>
              </div>
              <div>
                <p>🍽️</p>
                <h3><%= machine.capacity %></h3>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/machines/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.actu.fr/uploads/2021/01/142489619-233131581751207-2875209039377928422-n.jpg);">
  <div class="row justify-content-center" id="new-machine">
    <div class="col-md-12">
      <div class="form-color"> 
        <h1>Mettre mon appareil en location</h1>
      </div>
      <%= simple_form_for @machine do |f| %>
        <%= f.input :name, label: 'Titre de votre annonce' %>
        <%= f.input :category, label: "Type d'appareil ", collection: ["Barbecue", "Fondue", "Pierrade", "Plancha", "Raclette", "Autre"], include_blank: false, include_hidden: false %>
        <%= f.input :capacity, label: "Nombre de couverts 🍽️" %>
        <%= f.input :description, label: "Description de votre annonce" %>
        <%= f.input :condition, label: "Etat de votre appareil ⚙️", collection: ["Neuf", "Très bon état", "Bon état", "Moyen"] %>
        <%= f.input :address, label: "Votre adresse 🗺️" %>
        <%= f.input :price, label: "Prix de la location (par jour) 💸" %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, label:"Publier mon annonce", class: 'btn btn-discover' %>
      <% end %>
  </div>
</div>

app/views/machines/show.html.erb
<div class="container">
  <div class="row justify-content-around">

    <div class="col-7" id="form-product">
      <div class="product-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @machine.photo.key, crop: :fill %>')"></div>
      <div class="machine-info-row justify-content-around">
      </div>
      <div class="machine-info-row justify-content-around">
        <div class="spef justify-content-start align-middle">
          <div class="icon-align">
            <p>🗺️ <%=@machine.address%></p>
          </div>
          <!-- <p><%=@machine.address%></p> -->
        </div>
        <div class="spef justify-content-start">
        </div>
      </div>
      <div class="pl-1 ml-5 machine-info-row justify-content-around">
        <div class="spef justify-content-start">
          <div class="icon-align">
            <p>🍽️<%=@machine.capacity%></p>
          </div>
        </div>
        <div class="spef justify-content-start">
          <div class="icon-align">
            <p>⚙️<%=@machine.condition%></p>
          </div>
        </div>
        <div class="spef justify-content-start">
          <div class="icon-align">
            <p>💰<%=@machine.price%>€ / j</p>
          </div>
        </div>
      </div>
        <div id="description-font">
          <h4><%= @machine.name %></h4>
          <h4>---</h4>
          <p><%=@machine.description%></p>
        </div>
    </div>
    <div class="col-4 p-0">
      <div id="form-book" class="p-4 sticky-top p-6">
        <h2><strong>Réserver cet appareil</strong></h2>
        <div id="booking-form" data-price="<%= @machine.price %>">
          <%= simple_form_for [@machine, @booking] do |f| %>
            <%= f.input  :start_date, label: "Date de début 📅", as: :string, required: false, input_html: {id: "range_start"} %>
            <%= f.input  :end_date, label: "Date de fin 📅", as: :string, required: false, input_html: {id: "range_end"} %>
            <%= f.button :submit, class: 'w-100 mt-3 btn btn-discover' %>
          <% end %>
        </div>
        <div id="total-amount">
      </div>
      </div>
    </div>
  </div>
  <div id="back-machine"><%= link_to "Retourner à la sélection de machines", machines_path %></div>
</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<%= render "shared/homecards" %>
<br>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.actu.fr/uploads/2021/01/142489619-233131581751207-2875209039377928422-n.jpg);">
  <div class="container home-navbar-container">
    <div class="logo-banner">
      <%= cl_image_tag("logo_rb_p_ljuyun", width: 100, height: 100,) %>
      <p>Raclette, Plancha & Barbecue</p>
    </div>
    <h1 id="banner-title"></h1>
    <%= link_to "J'AI FAIM, JE LOUE", machines_path, class:"btn-discover" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_homecards.html.erb
<div class="row justify-content-around m-3">
  <div class="card-category col-12 col-lg-6 m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://m.bettybossi.ch/static/rezepte/x/bb_chch090801_0135a_x.jpg)">
    <h2>Raclette</h2>
  </div>
  <div class="card-category col-12 col-lg-6 m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1512594282804-b5f400408c9d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1050&q=80)">
    <h2>Fondue</h2>
  </div>
  <div class="card-category col-12 col-lg-6 m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://boucherie-dynamique.com/c/158-category_default/vos-soirees-pierrade.jpg)">
    <h2>Pierrade</h2>
  </div>
  <div class="card-category col-12 col-lg-6 m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940)">
    <h2>Barbecue</h2>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= cl_image_tag("logo_rb_p_ljuyun") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Louez vos appareils 🧀🥩", new_machine_path, class: "nav-link btn-navbar" %>
      </li>
      <li class="nav-item dropdown">
        <div class="user-login-btn">
          <i class="fas fa-bars", id="navbarDropdown", data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
          <% if user_signed_in? && current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <i class="fas fa-user", id="navbarDropdown", data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item"  %>
              <%= link_to "Mes appareils", machines_path, class: "dropdown-item"  %>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Inscription", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Connexion", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= simple_form_for :search, url: machines_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>